# -*- coding: utf-8 -*-
"""pca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4LE3CSoArYhGIlF8wB_LitBuEEHdqSE
"""

from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# load the iris dataset
iris = load_iris()

# create a PCA object with 2 components
pca = PCA(n_components=2)

# fit and transform the data
iris_pca = pca.fit_transform(iris.data)

# plot the transformed data
plt.scatter(iris_pca[:, 0], iris_pca[:, 1], c=iris.target)
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.show()